### ISSUE TITLE
Convert code fragments from images to text

### ISSUE THREAD

**Issue by Toparvion** [dmitrij-drandarov/JUnit5-Quick-Start-Guide-and-Advanced#1]
Thank you for the very useful guide!  
As its reader I'd suppose that it can be even more valuable if all the code fragments are presented as copy-able text paragraphs instead of pictures. The current form doesn't allow to select, copy and then search code extracts among other sources. Furthermore due to picture compression the overall quality of the text is much lower than it might be in case of pure text (since compression introduces a lot of visual 'noise').

**Comment by dmitrij-drandarov** [comment]
Thank you for the feedback.
I guess I will do that. I had a lot of problems with that GitHubs-Pages-Feature and formatting (I mean look at the commits..). So that was the easier solution back then. I even had a workaround for the compression but that doesn't work anymore.
So yeah: On my Todo-list :)

**Comment by Toparvion** [comment]
@dmitrij-drandarov, Thank you for the link to source code.
I used the same Github Pages static site generator for one of my projects (see http://toparvion.tech/) but didn't faced any problems with code formatting.
As a kind of workaround I'd advice to move the page from Github Pages to Github Wiki. It won't make the content less readable for users but will ease both the use and the administration. For instance, compare the aforementioned site with [this page](https://github.com/Toparvion/jmint/blob/master/README.md) - exactly the same Markdown content stands behind both of them and the latter doesn't seem worse (imho).

**Comment by dmitrij-drandarov** [comment]
I'd like to keep the Github-Pages Page but I will consider doing a wiki page parallel to Github-Pages.
Thanks for the advice :)

**Comment by dmitrij-drandarov** [comment]
Done ;)
Code not being auto-wrapped was a pain though. Had to refactor a lot. ><
